(async () => {
  await window.sharedDataReady;
  const results = [], test = (name, condition) => results.push({ name, ok: Boolean(condition) });
  const api = window.ExadexLocations;
  const migrate = (location, id = `test-${location}`) => api.migratePlacements({ id, location, locations: [location] });
  const frigo = migrate("Frigo labo")[0], freezer = migrate("-80°C")[0], bureau = migrate("Bureau")[0], culture = migrate("Culture L1")[0];
  test("sept salles fixes", api.rooms().length === 7);
  test("Frigo labo migre sous Laboratoire", frigo.roomId === "room-laboratoire" && frigo.locationId === "location-frigo-labo" && frigo.sublocationId === null);
  test("-80°C migre sous Pièce -80°C", freezer.roomId === "room-piece-80" && freezer.locationId === "location-80");
  test("Bureau reste direct", bureau.roomId === "room-bureau" && bureau.locationId === null);
  test("Culture L1 reste direct", culture.roomId === "room-culture-l1" && culture.locationId === null);
  test("aucune localisation Culture L1 homonyme", !api.catalog().locations.some(row => row.roomId === "room-culture-l1" && row.name === "Culture L1"));
  const once = api.migratePlacements({ id:"stable", location:"Frigo labo", locations:["Frigo labo"] });
  const twice = api.migratePlacements({ id:"stable", placements:once, location:"Frigo labo", locations:["Frigo labo"] });
  test("migration idempotente", JSON.stringify(once) === JSON.stringify(twice));
  const unknown = migrate("Armoire historique inconnue", "unknown")[0];
  test("ancienne valeur inconnue conservée", unknown.legacyValue === "Armoire historique inconnue");
  test("hiérarchie incompatible refusée", !api.validatePlacement({roomId:"room-bureau",locationId:"location-frigo-labo",sublocationId:null}));
  renderPlacementEditor([]);
  test("bloc vide sans erreur immédiate", placementsError.classList.contains("hidden") && document.querySelector("[data-placement-row-error]").classList.contains("hidden"));
  test("bloc vide bloqué avec message adapté", !validatePlacements(readPlacementEditor(),{onSubmit:true}) && document.querySelector("[data-placement-row-error]").textContent.includes("Veuillez sélectionner une salle"));
  renderPlacementEditor([{id:"direct-valid",roomId:"room-bureau",locationId:null,sublocationId:null}]);
  test("salle seule valide", validatePlacements(readPlacementEditor(),{onSubmit:true}));
  test("hiérarchie croisée signalée", !validatePlacements([{id:"cross",roomId:"room-bureau",locationId:"location-frigo-labo",sublocationId:null}],{onSubmit:true}) && placementsError.textContent.includes("hiérarchie incohérente"));
  renderPlacementEditor([{id:"visual",roomId:"room-bureau",locationId:null,sublocationId:null}]);
  const placementStyle=getComputedStyle(document.querySelector(".placement-row"));
  test("emplacement sans cadre ni fond", placementStyle.backgroundColor === "rgba(0, 0, 0, 0)" && placementStyle.borderTopWidth === "0px" && placementStyle.boxShadow === "none");
  document.querySelector('[data-view="locations"]').click();
  test("page principale à sept fiches", document.querySelectorAll("#locationGrid [data-room-id]").length === 7);
  document.querySelector('#locationGrid [data-room-id="room-laboratoire"]').click();
  test("Laboratoire affiche quatre localisations", document.querySelectorAll("#locationGrid [data-location-id]").length === 4);
  test("bouton ajout localisation", !document.querySelector('[data-add-hierarchy="location"]')?.disabled);
  test("lignes compactes sans aperçu de références", [...document.querySelectorAll("#locationGrid [data-location-id]")].every(row => !row.querySelector(".location-row-preview")));
  test("aperçu dédupliqué par item", (hierarchyPreview([{record:{id:"same",name:"Unique"}},{record:{id:"same",name:"Unique"}}]).match(/Unique/g)||[]).length === 1);
  test("actions absentes des salles fixes", !document.querySelector('[data-edit-hierarchy="room"], [data-delete-hierarchy="room"]'));
  test("actions présentes sur les localisations", [...document.querySelectorAll("#locationGrid [data-location-id]")].every(card => card.querySelector('[data-edit-hierarchy="location"]') && card.querySelector('[data-delete-hierarchy="location"]')));
  const actionMenuTrigger=document.querySelector("#locationGrid [data-location-id] [data-toggle-location-menu]");actionMenuTrigger.click();
  test("menu vertical ouvre Modifier et Supprimer sans sélectionner la ligne", actionMenuTrigger.getAttribute("aria-expanded")==="true" && !actionMenuTrigger.nextElementSibling.classList.contains("hidden") && selectedLocationId===null);
  const table = renderLocationDetailTable([{kind:"inventory",record:{id:"row",name:"Test",category:"Test",quantity:1,unit:"u",minStock:0,tags:[],placements:[]},placement:{roomId:"room-laboratoire",locationId:null,sublocationId:null}}]);
  test("colonnes de chemin avant Actions", /Tags[\s\S]*Localisation[\s\S]*Sous-localisation[\s\S]*Actions/.test(table));
  const directTable = renderLocationDetailTable([{kind:"inventory",record:{id:"direct",name:"Direct",category:"Test",quantity:1,unit:"u",minStock:0,tags:[]},placement:{roomId:"room-laboratoire",locationId:null,sublocationId:null}}],{hidePathColumns:true});
  test("table directe sans colonnes de chemin", !/Sous-localisation/.test(directTable) && !/<th>Localisation<\/th>/.test(directTable));
  document.querySelector('[data-add-hierarchy="location"]').click();
  test("ajout utilise la modale classique", document.querySelector("#hierarchyEntityDialog").open && document.querySelectorAll("#hierarchyEntityForm input").length === 1);
  document.querySelector("[data-close-hierarchy-entity]").click();
  const testLocation = hierarchyCatalog().locations.find(row => row.roomId === "room-laboratoire");
  sharedState.locationCatalog.sublocations.push({id:"sublocation-ui-test",locationId:testLocation.id,name:"Sous-localisation test"});
  if (!items.length) items.push(migrateItems([{id:"picker-test-item",name:"Item recherche test",category:inventoryCategories[0],quantity:1,unit:"u",minStock:0,location:"Bureau",locations:["Bureau"],references:{primary:{reference:"REF-PICKER"}},tags:[]}])[0]);
  items.push(...migrateItems([
    {id:"search-gants-s",name:"Gants nitrile taille S",category:inventoryCategories[0],quantity:1,unit:"u",minStock:0,location:"Bureau",locations:["Bureau"],references:{primary:{reference:"GNT-S"}},tags:[]},
    {id:"search-gants-m",name:"Gants nitrile taille M",category:inventoryCategories[0],quantity:1,unit:"u",minStock:0,location:"Bureau",locations:["Bureau"],references:{primary:{reference:"GNT-M"}},tags:[]},
    {id:"search-gants-steriles",name:"Gants stériles",category:inventoryCategories[0],quantity:1,unit:"u",minStock:0,location:"Bureau",locations:["Bureau"],references:{primary:{reference:"123-ABC"}},tags:[]}
  ]));
  selectedLocationId=testLocation.id; selectedSublocationId="sublocation-ui-test"; renderLocations();
  test("Ajouter un item actif avec un chemin sélectionné", !document.querySelector('[data-add-hierarchy="item"]')?.disabled);
  document.querySelector('[data-add-hierarchy="item"]').click();
  test("Ajouter un item ouvre le formulaire classique prérempli", dialog.open && !fields.itemId.value && readPlacementEditor().some(row=>row.roomId===testLocation.roomId&&row.locationId===testLocation.id&&row.sublocationId==="sublocation-ui-test"));
  dialog.close();
  openSublocationItemPicker();
  const searchInput=document.querySelector("#sublocationItemSearch"),fireInput=()=>searchInput.dispatchEvent(new Event("input",{bubbles:true}));
  test("champ vide affiche l’état initial", document.querySelector("#sublocationItemDialog").open && document.querySelector("#sublocationItemResults").textContent.includes("Saisissez un nom"));
  searchInput.value="g";fireInput();test("première lettre actualise immédiatement",document.querySelectorAll("[data-pick-sublocation-item]").length>=3);
  searchInput.value="gants";fireInput();test("recherche partielle par nom",document.querySelectorAll("[data-pick-sublocation-item]").length===3);
  searchInput.value="GANTS";fireInput();test("recherche insensible à la casse",document.querySelectorAll("[data-pick-sublocation-item]").length===3);
  searchInput.value="steriles";fireInput();test("recherche insensible aux accents",document.querySelectorAll("[data-pick-sublocation-item]").length===1);
  searchInput.value="123-ab";fireInput();test("recherche par référence principale",document.querySelectorAll("[data-pick-sublocation-item]").length===1);
  searchInput.value="123-a";fireInput();test("suppression d’un caractère actualise la liste",document.querySelectorAll("[data-pick-sublocation-item]").length===1);
  searchInput.value="aucun-resultat-possible";fireInput();test("absence de résultat explicitée",document.querySelector("#sublocationItemResults").textContent.includes("Aucun item trouvé pour cette recherche"));
  searchInput.value="gants";fireInput();document.querySelector("#clearSublocationItemSearch").click();test("effacement restaure l’état initial et le focus",searchInput.value===""&&document.activeElement===searchInput&&document.querySelector("#sublocationItemResults").textContent.includes("Saisissez un nom"));
  searchInput.value="Item recherche test";fireInput();
  test("recherche d’items en modale", document.querySelectorAll("[data-pick-sublocation-item]").length > 0);
  const pickerRect=document.querySelector("#sublocationItemDialog").getBoundingClientRect(),pickerResults=document.querySelector("#sublocationItemResults");
  test("recherche contenue sans débordement horizontal", pickerRect.left>=0 && pickerRect.right<=innerWidth && pickerResults.scrollWidth<=pickerResults.clientWidth);
  const inputRect=searchInput.getBoundingClientRect(),resultsRect=pickerResults.getBoundingClientRect();
  test("résultats sous le champ en pleine largeur",resultsRect.top>=inputRect.bottom&&Math.abs(resultsRect.width-inputRect.width)<2);
  items.push(...migrateItems(Array.from({length:45},(_,index)=>({id:`scroll-search-${index}`,name:`Scroll recherche ${index}`,category:inventoryCategories[0],quantity:1,unit:"u",minStock:0,location:"Bureau",locations:["Bureau"],references:{primary:{reference:`SCROLL-${index}`}},tags:[]}))));
  searchInput.value="scroll recherche";fireInput();test("longue liste seule scrollable",getComputedStyle(pickerResults).overflowY==="auto"&&pickerResults.scrollHeight>pickerResults.clientHeight);
  searchInput.value="Item recherche test";fireInput();
  const pickerItem=items.find(row=>row.id==="picker-test-item");
  if (pickerItem) {
    const before=JSON.stringify(pickerItem.placements||[]),itemCountBefore=items.length;
    document.querySelector(`[data-pick-sublocation-item="${CSS.escape(pickerItem.id)}"]`)?.click();
    const pending=readPlacementEditor().some(row=>row.sublocationId==="sublocation-ui-test");
    test("sélection ouvre l’item existant sans création", fields.itemId.value===pickerItem.id&&items.length===itemCountBefore);
    test("chemin ajouté seulement dans le formulaire", pending && JSON.stringify(pickerItem.placements||[])===before);
    dialog.close();
  }
  const target={id:"target",roomId:"room-culture-l1",locationId:"location-frigo-culture-l1",sublocationId:"sub-target"};
  const originalDirect=[{id:"direct",roomId:"room-culture-l1",locationId:null,sublocationId:null}],refined=preparePlacementsForTarget(originalDirect,target);
  test("emplacement direct de même salle précisé", refined.length===1 && refined[0].id==="direct" && refined[0].sublocationId==="sub-target");
  test("préremplissage temporaire sans mutation source", originalDirect[0].locationId===null && originalDirect[0].sublocationId===null);
  const otherRoom=preparePlacementsForTarget([{id:"lab",roomId:"room-laboratoire",locationId:null,sublocationId:null}],target);
  test("autre salle conservée et nouveau chemin ajouté", otherRoom.length===2 && otherRoom[0].id==="lab" && otherRoom[1].sublocationId==="sub-target");
  const exact=preparePlacementsForTarget([{id:"exact",...target}],target);
  test("chemin exact non dupliqué", exact.length===1);
  const precise=preparePlacementsForTarget([{id:"precise",roomId:"room-culture-l1",locationId:"location-20-culture-l1",sublocationId:null}],target);
  test("chemin précis existant non écrasé", precise.length===2 && precise[0].locationId==="location-20-culture-l1");
  openHierarchyEntityModal("sublocation","sublocation-ui-test");
  document.querySelector("#hierarchyEntityName").value="Sous-localisation renommée";
  document.querySelector("#hierarchyEntityForm").requestSubmit();
  test("renommage conserve l’identifiant", hierarchySublocation("sublocation-ui-test")?.name === "Sous-localisation renommée");
  requestHierarchyDeletion("sublocation","sublocation-ui-test",document.body);
  document.querySelector("#confirmDeleteBtn").click(); await new Promise(resolve=>setTimeout(resolve,160));
  test("suppression vide après confirmation", !hierarchySublocation("sublocation-ui-test"));
  sharedState.locationCatalog.sublocations.push({id:"sublocation-blocked-test",locationId:testLocation.id,name:"Sous-localisation occupée"});
  items[0].placements.push({id:"placement-blocked-test",roomId:testLocation.roomId,locationId:testLocation.id,sublocationId:"sublocation-blocked-test"});
  requestHierarchyDeletion("sublocation","sublocation-blocked-test",document.body);
  document.querySelector("#confirmDeleteBtn").click(); await new Promise(resolve=>setTimeout(resolve,160));
  test("suppression occupée remonte l’item vers la localisation", !hierarchySublocation("sublocation-blocked-test") && items[0].placements.some(row=>row.locationId===testLocation.id&&row.sublocationId===null));
  const fixtureItems=Array.from({length:20},(_,index)=>({id:`fixture-${index}`,quantity:index+1,placements:[{id:`p-${index}`,roomId:"room-culture-l1",locationId:"loc-fixture",sublocationId:"sub-fixture"}]})),fixtureIds=fixtureItems.map(row=>row.id),fixtureStocks=fixtureItems.map(row=>row.quantity),reparentedSubs=reparentItemsForHierarchyDeletion(fixtureItems,"sublocation","sub-fixture"),reparentedLocs=reparentItemsForHierarchyDeletion(fixtureItems,"location","loc-fixture");
  test("helper isolé conserve les 20 items et stocks", reparentedSubs.length===20&&JSON.stringify(reparentedSubs.map(row=>row.id))===JSON.stringify(fixtureIds)&&JSON.stringify(reparentedSubs.map(row=>row.quantity))===JSON.stringify(fixtureStocks));
  test("helper isolé remonte 20 items vers la localisation", reparentedSubs.every(item=>item.placements.length===1&&item.placements[0].locationId==="loc-fixture"&&item.placements[0].sublocationId===null));
  test("helper isolé remonte directs et descendants vers la salle", reparentedLocs.every(item=>item.placements.length===1&&item.placements[0].roomId==="room-culture-l1"&&item.placements[0].locationId===null&&item.placements[0].sublocationId===null));
  closeDeleteConfirmation({force:true});
  const failed = results.filter(row => !row.ok), host = document.createElement("pre");
  host.id = "hierarchyTestResults"; host.textContent = JSON.stringify({passed:results.length-failed.length,failed:failed.length,results},null,2); document.body.append(host);
})();
