(() => {
  const rules=window.ExadexClientSampleRules,lines=[],test=(name,fn)=>{try{fn();lines.push(`✓ ${name}`)}catch(error){lines.push(`✗ ${name}: ${error.message}`)}},assert=(condition,message)=>{if(!condition)throw new Error(message)};
  test("unités catégories",()=>{assert(rules.getCreatedSampleUnit("Fixation (galette)")==="mg","galette");assert(rules.getCreatedSampleUnit("Fixation (tissu)")==="mg","tissu");assert(rules.getCreatedSampleUnit("cDNA")==="µL","cDNA");assert(rules.getCreatedSampleUnit("Sécrétion")==="mL","sécrétion")});
  test("ARN Qiazol",()=>{assert(rules.getCreatedSampleUnit("ARN",true)==="mg","avec Qiazol");assert(rules.getCreatedSampleUnit("ARN",false)==="µL","sans Qiazol")});
  test("libellé du tag ARN depuis les options sauvegardées",()=>{assert(rules.getClientSampleCategoryLabel({category:"ARN",arnQiazol:true,arnBead:false})==="ARN + Qiazol","Qiazol");assert(rules.getClientSampleCategoryLabel({category:"ARN",arnQiazol:true,arnBead:true})==="ARN + Qiazol","bille");assert(rules.getClientSampleCategoryLabel({category:"ARN",arnQiazol:false,arnBead:false})==="ARN extrait","extrait")});
  test("migration sans perte",()=>{const out=rules.migrateClientSamples([{id:"old",type:"created_sample",name:"X",category:"Galette agarose",measureValue:12,measureUnit:"mg",notes:"note",location:"Bureau",clientCode:"C1"}])[0];assert(out.category==="Fixation (galette)"&&out.measureValue===12&&out.measureUnit==="mg"&&out.notes==="note"&&out.location==="Bureau","migration destructive")});
  test("ancienne catégorie ambiguë conservée",()=>{const out=rules.migrateClientSamples([{id:"x",type:"created_sample",name:"X",category:"Ancienne catégorie",measureValue:2,measureUnit:"µL",clientCode:"C1"}])[0];assert(out.category==="Ancienne catégorie"&&out.measureUnit==="µL","valeur inventée")});
  test("valeur vidée seulement au changement d’unité",()=>{const f=rules.fields;f.sampleCategory.value="Fixation (galette)";f.sampleMeasureValue.dataset.measureUnit="mg";f.sampleMeasureValue.value="3";rules.syncSampleMeasureLabel({clearOnUnitChange:true});assert(f.sampleMeasureValue.value==="3","mg vers mg vidé");f.sampleCategory.value="cDNA";rules.syncSampleMeasureLabel({clearOnUnitChange:true});assert(f.sampleMeasureValue.value==="","mg vers µL non vidé")});
  test("règles ARN",()=>{const f=rules.fields;f.sampleType.value="created_sample";f.sampleCategory.value="ARN";f.sampleArnQiazol.checked=false;f.sampleArnBead.checked=true;rules.syncSampleMeasureLabel();assert(!f.sampleArnBead.checked&&f.sampleArnBead.disabled&&!f.sampleArnNotesHint.classList.contains("hidden"),"état incorrect")});
  test("ordre exact de l’en-tête",()=>{const labels=[...document.querySelectorAll(".client-study-list-head span")].map(node=>node.textContent.trim());assert(labels.join("|")==="Produit|Quantité/Catégorie|Localisation|Date",labels.join("|"))});
  test("grille commune en-tête et lignes",()=>{const host=document.querySelector(".client-study-groups"),group=document.createElement("section"),row=document.createElement("button");group.className="client-group";row.className="client-sample-row";row.innerHTML="<div></div><span class='client-table-cell'><span class='client-quantity-category-value'>3 g</span></span><span></span><span></span>";group.appendChild(row);host.appendChild(group);const head=document.querySelector(".client-study-list-head"),headStyle=getComputedStyle(head),rowGrid=getComputedStyle(row).gridTemplateColumns;if(innerWidth<=680){assert(headStyle.display==="none"&&rowGrid.split(" ").length===1,"grille mobile incorrecte")}else{const headGrid=headStyle.gridTemplateColumns;assert(headGrid===rowGrid,`${headGrid} ≠ ${rowGrid}`);const headingX=head.children[1].getBoundingClientRect().left,valueX=row.children[1].getBoundingClientRect().left;assert(Math.abs(headingX-valueX)<0.6,`axes ${headingX}/${valueX}`)}group.remove()});
  test("cases ARN associées et alignées",()=>{const labels=[...document.querySelectorAll("#sampleArnOptions label")],checks=labels.map(label=>label.querySelector("input"));assert(labels[0].htmlFor==="sampleArnQiazol"&&labels[1].htmlFor==="sampleArnBead","association label");assert(checks.every(check=>getComputedStyle(check).width==="18px"),"largeur flottante");assert(Math.abs(checks[0].getBoundingClientRect().left-checks[1].getBoundingClientRect().left)<0.6,"cases non alignées")});
  const result=document.createElement("pre");result.id="clientSampleTestResult";result.textContent=lines.join("\n");document.body.appendChild(result);document.body.dataset.clientSampleTestsFailed=String(lines.some(line=>line.startsWith("✗")));
})();
