(function(root,factory){const api=factory(root);if(typeof module!=="undefined"&&module.exports)module.exports=api;root.ExadexAssistantDataSources=api;})(typeof window!=="undefined"?window:globalThis,function(root){
  "use strict";
  const clone=value=>JSON.parse(JSON.stringify(value??null));
  const array=value=>Array.isArray(value)?value:[];
  const normalize=value=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
  const safeArray=name=>{try{return clone(array(root[name]));}catch{return[];}};
  function inventoryDataSource(input){return array(input??safeArray("items")).map(item=>({type:"item",id:String(item.id),name:String(item.name||""),section:"inventory",source:item,relations:{supplierContactId:item.supplierContactId||null},navigation:{kind:"item",id:String(item.id)}}));}
  function clientStudiesDataSource(input={}){const clients=array(input.clients??safeArray("clients")),products=array(input.products??safeArray("clientSamples"));return clients.map(client=>{const related=products.filter(product=>product.clientId===client.id||(client.normalizedKey&&product.normalizedClientKey===client.normalizedKey));return{type:"client_study",id:String(client.id),name:String(client.canonicalCode||client.normalizedKey||client.id),section:"samples",source:client,relations:{productIds:related.map(row=>row.id)},products:related.map(product=>({type:"client_product",id:String(product.id),name:String(product.name||product.baseName||""),section:"samples",source:product,relations:{clientId:client.id},navigation:{kind:"clientProduct",id:String(product.id)}})),navigation:{kind:"clientStudy",id:String(client.id)}};});}
  function suppliersDataSource(input={}){const contacts=array(input.contacts??safeArray("supplierContacts")),items=array(input.items??safeArray("items")),orders=array(input.orders??safeArray("orders"));const structured=contacts.map(contact=>({type:"supplier",id:String(contact.id),name:String(contact.company||""),section:"contacts",source:contact,aliases:array(contact.aliases),relations:{itemIds:items.filter(item=>item.supplierContactId===contact.id).map(row=>row.id),orderIds:[]},navigation:{kind:"supplier",id:String(contact.id)}}));const known=new Set(structured.flatMap(row=>[row.name,...row.aliases].map(normalize)));[...items.map(item=>item.references?.primary?.supplier||item.supplier),...orders.map(order=>order.supplier)].filter(Boolean).forEach((name,index)=>{if(known.has(normalize(name)))return;known.add(normalize(name));structured.push({type:"supplier",id:`inferred-supplier-${index}`,name:String(name),section:"inventory",source:{company:String(name),phone:"",coordinates:[]},aliases:[],relations:{itemIds:items.filter(item=>normalize(item.references?.primary?.supplier||item.supplier)===normalize(name)).map(row=>row.id),orderIds:orders.filter(order=>normalize(order.supplier)===normalize(name)).map(row=>row.id)},navigation:null});});return structured;}
  function ordersDataSource(input,inventoryInput){const inventory=array(inventoryInput??safeArray("items"));return array(input??safeArray("orders")).map(order=>{const linked=inventory.find(item=>String(item.id)===String(order.inventoryItemId))||null,nested=[order.lines,order.items,order.products,order.orderLines].find(Array.isArray)||[],fallback={id:`${order.id}-line-1`,name:order.itemName||order.newItemData?.name||linked?.name||"",quantity:order.requestedQuantity??order.quantity,receivedQuantity:order.receivedQuantity,reference:order.reference||order.catalogReference||order.newItemData?.reference||linked?.references?.primary?.reference||"",supplier:order.supplier||order.newItemData?.supplier||linked?.references?.primary?.supplier||linked?.supplier||"",manufacturer:order.manufacturer||order.newItemData?.manufacturer||linked?.manufacturer||"",brand:order.brand||order.newItemData?.brand||linked?.brand||"",category:order.category||order.newItemData?.category||linked?.category||"",notes:order.notes||order.newItemData?.notes||linked?.notes||"",sourcePath:"order"},lines=(nested.length?nested:[fallback]).map((line,index)=>({type:"order_line",id:String(line.id||`${order.id}-line-${index+1}`),name:String(line.name||line.itemName||line.designation||line.description||fallback.name),source:{...line},search:{reference:line.reference||line.catalogReference||line.sku||fallback.reference,supplier:line.supplier||fallback.supplier,manufacturer:line.manufacturer||fallback.manufacturer,brand:line.brand||fallback.brand,category:line.category||fallback.category,notes:line.notes||line.comment||fallback.notes,quantity:line.quantity??line.requestedQuantity??fallback.quantity},sourcePath:nested.length?"nested_line":"order"}));return{type:"order",id:String(order.id),name:String(order.itemName||order.newItemData?.name||linked?.name||order.id),section:"orders",source:order,lines,relations:{itemId:order.inventoryItemId||null},navigation:{kind:"order",id:String(order.id)}};});}
  function locationsDataSource(input){const catalog=input??(()=>{try{return clone(root.inventoryLocationCatalog)||{};}catch{return{};}})(),rooms=array(catalog.rooms),locations=array(catalog.locations),sublocations=array(catalog.sublocations);return[...rooms.map(room=>({type:"location",level:"room",id:String(room.id),name:String(room.name),section:"locations",source:room,navigation:{kind:"location",id:String(room.id)}})),...locations.map(location=>({type:"location",level:"location",id:String(location.id),name:String(location.name),section:"locations",source:location,relations:{roomId:location.roomId},navigation:{kind:"location",id:String(location.id)}})),...sublocations.map(location=>({type:"location",level:"sublocation",id:String(location.id),name:String(location.name),section:"locations",source:location,relations:{locationId:location.locationId},navigation:{kind:"location",id:String(location.id)}}))];}
  function historyDataSource(input){return array(input??safeArray("applicationHistory")).map((entry,index)=>({type:"history",id:String(entry.id||entry.operationId||`history-${index}`),name:String(entry.action||"Historique"),section:"history",source:entry,navigation:{kind:"history"}}));}
  function usersDataSource(input){return array(input??safeArray("applicationUsers")).map(user=>({type:"user",id:String(user.id||user.name),name:String(user.name||""),section:"users",source:user,navigation:null}));}
  function snapshot(overrides={}){return{inventory:inventoryDataSource(overrides.items),studies:clientStudiesDataSource({clients:overrides.clients,products:overrides.clientSamples}),suppliers:suppliersDataSource({contacts:overrides.supplierContacts,items:overrides.items,orders:overrides.orders}),orders:ordersDataSource(clone(overrides.orders),clone(overrides.items)),locations:locationsDataSource(overrides.locationCatalog),history:historyDataSource(overrides.history),users:usersDataSource(overrides.users)};}
  return{clone,normalize,inventoryDataSource,clientStudiesDataSource,suppliersDataSource,ordersDataSource,locationsDataSource,historyDataSource,usersDataSource,snapshot};
});
