(function(root,factory){const variants=root.ExadexScientificVariants||(typeof require==="function"?require("./scientific_variants.js"):null);const api=factory(variants);if(typeof module!=="undefined"&&module.exports)module.exports=api;root.ExadexInventoryAssistant=api;})(typeof window!=="undefined"?window:globalThis,function(ScientificVariants){
  "use strict";
  const SYNONYMS={
    serum:["sérum","fbs","svf"],trypsine:["trypsin"],pbs:["phosphate buffered saline"],dmem:["dulbecco modified eagle medium","dulbeccos modified eagle medium"],anticorps:["antibody","antibodies","ac"],bouteille:["flacon"],frigo:["réfrigérateur","refrigerateur","4 c"],congelateur:["congélateur","freezer"],milieu:["medium","media","milieu de culture"]
  };
  const SCIENTIFIC_SYNONYMS={
    "collagene 6":["collagène vi","collagen vi","collagène 6","collagen 6","col6","col vi","col6a1","col6a2","col6a3"]
  };
  const ROMAN={i:1,ii:2,iii:3,iv:4,v:5,vi:6};
  const PHRASES=["est ce que j ai","est ce que jai","est ce qu on","est ce que","estc eque","avons nous","il y a","je vais","j en ai","jen ai","peux tu","tu peux","trouve moi","se trouve","ai je"];
  const STOP=new Set("a ai au aux avons avez avec besoin ce cette cherche combien dans de des du elle en est et il item items je j l la laboratoire le les me moi nous on ou où produit produits quel quelle quels quelles reste restantes restant se stock stocks sur trouve trouver tu un une vous y encore peut peux recherche chercher inventaire disponible disponibles vais utiliser utilise utilisee utilises utilisé utilisée utilisés utilisées assez suffisant suffisante suffisamment faut faudra avoir apres après".split(" "));
  const CONTEXT_WORDS=new Set(["milieu","produit","item"]),TYPE_WORDS=new Set(["anticorps","antibody","enzyme","seringue"]),QUALIFIERS=new Set(["low","high","sans","glucose","glutamax","f12"]);
  const MUTATION=/\b(ajout(?:e|er)?|supprim(?:e|er)?|modifi(?:e|er)?|deplac(?:e|er)?|commande(?:r)?|mets?|mettre|retire(?:r)?|corrige(?:r)?)\b/i;
  const UNIT_ALIASES={ul:"µL",µl:"µL",ml:"mL",l:"L",ug:"µg",µg:"µg",mg:"mg",g:"g"};
  const UNIT_FACTORS={"µL":{dimension:"volume",factor:0.001},mL:{dimension:"volume",factor:1},L:{dimension:"volume",factor:1000},"µg":{dimension:"mass",factor:0.001},mg:{dimension:"mass",factor:1},g:{dimension:"mass",factor:1000}};
  const normalize=value=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("fr").replace(/[’']/g," ").replace(/[^a-z0-9%µ+./-]+/g," ").replace(/\s+/g," ").trim();
  const singular=word=>word==="anticorps"?word:word.length>4&&word.endsWith("s")&&!word.endsWith("ss")?word.slice(0,-1):word;
  const titleRoman=number=>Object.entries(ROMAN).find(([,value])=>value===Number(number))?.[0]?.toUpperCase()||String(number);
  function repaired(question){let value=` ${normalize(question).replace(/\bestc\s+eque\b/g,"est ce que").replace(/\blanticorps\b/g,"l anticorps").replace(/\bjen\b/g,"j en").replace(/\bjai\b/g,"j ai").replace(/\best-(il|elle)\b/g,"est $1").replace(/\ba-t-on\b/g,"a t on").replace(/\bavons-nous\b/g,"avons nous").replace(/(\d)(µl|ul|ml|ug|µg|mg|g|l)\b/g,"$1 $2")} `;PHRASES.forEach(phrase=>{value=value.replace(new RegExp(`\\b${phrase.replace(/ /g,"\\s+")}\\b`,"g")," ");});return value.replace(/\s+/g," ").trim();}
  function quantityFrom(question){const text=normalize(question).replace(/(\d)(µl|ul|ml|ug|µg|mg|g|l)\b/g,"$1 $2"),match=text.match(/(?:^|\s)(\d+(?:[.,]\d+)?)\s*(µl|ul|ml|l|µg|ug|mg|g)\b/i);if(!match)return null;return{value:Number(match[1].replace(",",".")),unit:UNIT_ALIASES[match[2].toLowerCase()]||match[2]};}
  function detectScientific(text){const normalized=normalize(text),col6=/\b(?:col\s*6|collagene\s*(?:vi|6)|collagen\s*(?:vi|6))\b/.test(normalized);return col6?{key:"collagene 6",label:"Collagène VI",variants:SCIENTIFIC_SYNONYMS["collagene 6"].map(normalize)}:null;}
  function detectIntent(question,quantity){const q=normalize(question).replace(/-/g," "),sufficient=Boolean(quantity&&/\b(assez|suffisant|suffisante|suffisamment|faut|utiliser|utilise|besoin|necessaire)\b/.test(q));if(sufficient)return"sufficiency";if(/\b(ou|localisation|salle|se trouve|sont)\b/.test(q))return"location";if(/\b(combien|quantite|stock|reste)\b/.test(q))return"quantity";if(/\b(avons|avez|a t on|est ce|y a|encore|j ai|jai)\b/.test(q))return"existence";return"search";}
  function analyze(question,context={}){const original=String(question||""),quantity=quantityFrom(original),scientific=detectScientific(original),intent=detectIntent(original,quantity),normalizedOriginal=normalize(original).replace(/-/g," "),intentFlags={existence:/\b(avons|avez|est ce|y a|j ai|jai|encore)\b/.test(normalizedOriginal),quantity:/\b(combien|quantite|stock|reste)\b/.test(normalizedOriginal),location:/\b(ou|où|localisation|salle|trouve)\b/.test(normalizedOriginal),sufficiency:intent==="sufficiency"},clean=repaired(original),raw=clean.split(" ").filter(Boolean),unitToken=quantity?normalize(quantity.unit):"";let tokens=raw.filter(token=>!/^\d+(?:[.,]\d+)?$/.test(token)&&token!==unitToken&&!STOP.has(token));tokens=tokens.map(singular).filter(Boolean);const typeTerms=tokens.filter(token=>TYPE_WORDS.has(token)),qualifiers=tokens.filter(token=>QUALIFIERS.has(token));let productTerms=tokens.filter(token=>!TYPE_WORDS.has(token)&&!QUALIFIERS.has(token)&&!CONTEXT_WORDS.has(token));if(scientific){productTerms=productTerms.filter(token=>!/^col(?:lagene|lagen)?$/.test(token)&&token!=="6"&&token!=="vi");qualifiers.push("collagene","6");}if(!productTerms.length&&!typeTerms.length&&!scientific&&tokens.includes("milieu"))productTerms=["milieu"];const followUp=!productTerms.length&&!scientific&&/\b(il|elle|en|sa|son|ce produit|cet item)\b/.test(normalize(original)),ambiguous=followUp&&(!Array.isArray(context.lastItemIds)||context.lastItemIds.length!==1);const label=scientific?[...typeTerms,scientific.label].join(" "):[...typeTerms,...productTerms,...qualifiers].join(" ").replace(/\bf12\b/i,"F12").trim();const confidence=label?(scientific||productTerms.length?"high":"medium"):followUp&&!ambiguous?"context":"low";return{original,intent,intentFlags,productTerms,typeTerms,qualifiers:[...new Set(qualifiers)],quantity,scientific,ambiguousTerms:ambiguous?["référence au dernier résultat"]:[],confidence,label:label||"",followUp,contextItemIds:followUp&&!ambiguous?context.lastItemIds:[]};}
  function expansions(words){const out=new Set(words.map(normalize));Object.entries(SYNONYMS).forEach(([key,values])=>{const family=[key,...values].map(normalize);if(family.some(value=>words.some(word=>value===word||value.includes(word))))family.forEach(value=>out.add(value));});words.flatMap(word=>ScientificVariants?.variants?.(word)||[]).forEach(value=>out.add(normalize(value)));return[...out];}
  function distance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old;}}return row[b.length];}
  const list=value=>Array.isArray(value)?value:[value].filter(Boolean);
  function documentFor(item){const primary=item?.references?.primary||{},secondary=list(item?.references?.secondary),aliases=[...list(item.aliases),...list(item.synonyms),...list(item.otherNames)];return{name:normalize(item.name),reference:normalize([primary.reference,item.reference,...secondary.map(row=>row?.reference)].filter(Boolean).join(" ")),aliases:normalize(aliases.join(" ")),category:normalize([item.category,item.subcategory,item.type].filter(Boolean).join(" ")),supplier:normalize([primary.supplier,item.supplier,item.manufacturer].filter(Boolean).join(" ")),description:normalize([item.description,...list(item.tags)].filter(Boolean).join(" ")),notes:normalize([item.notes,primary.notes,...secondary.map(row=>row?.notes)].filter(Boolean).join(" ")),location:normalize([item._assistantLocation,item.location,...list(item.locations)].filter(Boolean).join(" "))};}
  function scientificMatch(doc,scientific){if(!scientific)return true;const haystack=`${doc.name} ${doc.aliases} ${doc.reference}`;if(/collagenase|collagenase/.test(haystack))return false;const variants=scientific.variants;return variants.some(value=>haystack.includes(value))||/\bcol6a[123]\b/.test(haystack);}
  function contradiction(doc,analysis){const name=doc.name;if(analysis.qualifiers.includes("low")&&(/\bhigh\b/.test(name)||/sans glucose/.test(name)))return true;if(analysis.qualifiers.includes("high")&&(/\blow\b/.test(name)||/sans glucose/.test(name)))return true;if(analysis.qualifiers.includes("sans")&&(/\blow\b|\bhigh\b/.test(name)))return true;if(analysis.typeTerms.includes("anticorps")&&!/anticorp|antibody|\bac\b/.test(`${name} ${doc.category} ${doc.description}`))return true;if(analysis.scientific&&!scientificMatch(doc,analysis.scientific))return true;return false;}
  function scoreItem(item,analysis){const doc=documentFor(item);if(contradiction(doc,analysis))return{item,score:-Infinity,reasons:["contradiction"]};const product=expansions(analysis.productTerms),qualifiers=analysis.qualifiers.filter(value=>!["collagene","6"].includes(value)),searchTerms=[...analysis.typeTerms,...product,...qualifiers],label=normalize(analysis.label);let score=0,reasons=[];if(label&&doc.name.replace(/-/g," ").replace(/\s+/g," ")===label){score=1200;reasons.push("exact-name");}if(label&&doc.reference.split(" ").includes(label)){score=Math.max(score,1100);reasons.push("exact-reference");}if(analysis.scientific&&scientificMatch(doc,analysis.scientific)){score+=800;reasons.push("scientific-target");}analysis.productTerms.forEach(term=>{if(doc.name.includes(term))score+=260;else if(doc.reference.includes(term))score+=240;else if(doc.aliases.includes(term))score+=220;else if(doc.category.includes(term)||doc.supplier.includes(term))score+=80;else if(doc.description.includes(term))score+=55;else if(doc.notes.includes(term)||doc.location.includes(term))score+=15;});analysis.typeTerms.forEach(term=>{if(doc.name.includes(term)||doc.category.includes(term)||doc.aliases.includes(term))score+=180;});qualifiers.forEach(term=>{if(doc.name.includes(term)||doc.aliases.includes(term)||doc.description.includes(term))score+=220;else score-=180;});if(analysis.productTerms.length&&analysis.productTerms.every(term=>doc.name.includes(term)))score+=300;if(score<300)analysis.productTerms.forEach(term=>{if(term.length>=4&&doc.name.split(/[ ./-]+/).some(word=>Math.abs(word.length-term.length)<=1&&distance(word,term)<=1)){score+=320;reasons.push("fuzzy");}});if(searchTerms.length===0)score=-Infinity;return{item,score,reasons};}
  function searchAnalysis(analysis,items,options={}){if(!Array.isArray(items))return{error:"unavailable",analysis,results:[]};if(analysis.ambiguousTerms.length)return{analysis,ambiguous:true,results:[]};if(analysis.contextItemIds.length)return{analysis,results:items.filter(item=>analysis.contextItemIds.includes(item.id)).map(item=>({item,score:1200,reasons:["context"]}))};if(!analysis.label)return{analysis,generic:true,results:[]};const ranked=items.map(item=>scoreItem(item,analysis)).filter(row=>Number.isFinite(row.score)&&row.score>=(options.minimumScore||300)).sort((a,b)=>b.score-a.score||String(a.item.name).localeCompare(String(b.item.name),"fr"));if(!ranked.length)return{analysis,results:[]};const top=ranked[0].score,margin=top>=900?80:top>=650?140:70,results=ranked.filter(row=>row.score>=top-margin).slice(0,options.limit||3);return{analysis,results,alternatives:ranked.filter(row=>!results.includes(row)&&row.score>=300).slice(0,3)};}
  function search(question,items,options={}){return searchAnalysis(analyze(question,options.context||{}),items,options);}
  function convertQuantity(value,from,to){const a=UNIT_FACTORS[from],b=UNIT_FACTORS[to];if(!a||!b||a.dimension!==b.dimension)return null;return value*a.factor/b.factor;}
  const fr=value=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:6}).format(value);
  function rowFor(item,adapters,requestedUnit){let info=adapters.stockInfo?adapters.stockInfo(item,requestedUnit):null;if(!info&&adapters.stockText){const display=adapters.stockText(item),match=String(display).match(/^\s*(-?\d+(?:[.,]\d+)?)\s+(.+)$/);info={display,quantity:match?Number(match[1].replace(",",".")):null,unit:match?match[2]:"unité",convertible:true};}const numeric=info?.quantity===null||info?.quantity===undefined?NaN:Number(info.quantity),unit=info?.unit||"unité",stockText=info?.display||(Number.isFinite(numeric)?`${fr(numeric)} ${unit}`:"Stock non renseigné");return{id:item.id,name:item.name,stock:stockText,stockQuantity:Number.isFinite(numeric)?numeric:null,stockUnit:unit,convertible:info?.convertible!==false,location:adapters.locationText?adapters.locationText(item):(item.location||"Sans localisation")};}
  function sufficiencyText(row,requested,label){if(row.stockQuantity===null||!row.convertible)return`${row.stock} de ${label} sont enregistrés, mais la quantité disponible n’est pas suffisamment renseignée pour confirmer si ${fr(requested.value)} ${requested.unit} sont disponibles.`;const available=convertQuantity(row.stockQuantity,row.stockUnit,requested.unit);if(available===null)return`${row.stock} de ${label} sont enregistrés, mais l’unité disponible ne permet pas de confirmer si ${fr(requested.value)} ${requested.unit} sont disponibles.`;const delta=Math.round((available-requested.value)*1e6)/1e6;if(delta>0)return`Oui. Nous avons ${fr(available)} ${requested.unit} de ${label} disponibles. Après une utilisation de ${fr(requested.value)} ${requested.unit}, il resterait ${fr(delta)} ${requested.unit}.`;if(delta===0)return`Oui, la quantité est exactement suffisante : ${fr(available)} ${requested.unit} disponibles pour ${fr(requested.value)} ${requested.unit} nécessaires. Il ne resterait plus de stock après utilisation.`;return`Non. Il reste ${fr(available)} ${requested.unit} de ${label}, soit ${fr(Math.abs(delta))} ${requested.unit} de moins que les ${fr(requested.value)} ${requested.unit} nécessaires.`;}
  function answer(question,items,adapters={},options={}){if(MUTATION.test(normalize(question)))return{kind:"readonly",text:"Je peux rechercher et consulter l’inventaire, mais je ne peux pas modifier les données.",items:[],context:{lastItemIds:[]}};const analysis=analyze(question,options.context||{}),found=searchAnalysis(analysis,items);if(found.error)return{kind:"error",text:"Je ne peux pas consulter l’inventaire pour le moment. Veuillez réessayer dans quelques instants.",items:[],analysis,context:{lastItemIds:[]}};if(found.ambiguous)return{kind:"clarify",text:"De quel item parlez-vous ?",items:[],analysis,context:options.context||{lastItemIds:[]}};if(found.generic)return{kind:"generic",text:"Je n’ai pas identifié le produit recherché. Pouvez-vous préciser son nom, sa référence ou sa catégorie ?",items:[],analysis,context:{lastItemIds:[]}};if(!found.results.length){const subject=analysis.label||"ce produit";return{kind:"empty",text:analysis.scientific?`Je n’ai trouvé aucun ${subject} correspondant clairement dans l’inventaire.`:`Je n’ai trouvé aucun item correspondant à « ${subject} » dans l’inventaire.`,items:[],analysis,context:{lastItemIds:[]}};}const selected=found.results,rows=selected.map(({item})=>rowFor(item,adapters,analysis.quantity?.unit)),label=analysis.label||rows[0].name,first=rows[0];let text;if(analysis.intent==="sufficiency"&&analysis.quantity)text=sufficiencyText(first,analysis.quantity,label);else if(selected.length===1&&analysis.intentFlags.existence&&(analysis.intentFlags.quantity||analysis.intentFlags.location))text=first.stockQuantity===0?`Le ${first.name} est enregistré, mais son stock est épuisé.\n\n📍 ${first.location}`:`Oui, nous avons du ${first.name}. Le stock disponible est de ${first.stock}.\n\n📍 ${first.location}`;else if(selected.length===1&&analysis.intent==="existence")text=first.stockQuantity===0?`Le ${first.name} est bien enregistré dans l’inventaire, mais son stock est actuellement épuisé.`:`Oui, nous avons du ${first.name}. Le stock disponible est de ${first.stock}.`;else if(selected.length===1&&analysis.intent==="location")text=`Le ${first.name} se trouve ici :\n\n📍 ${first.location}`;else if(selected.length===1&&analysis.intent==="quantity")text=first.stockQuantity===0?`Le ${first.name} est actuellement en stock épuisé.`:`Il reste actuellement ${first.stock} de ${first.name}.`;else if(selected.length===1)text=`J’ai trouvé « ${first.name} » dans l’inventaire.`;else text=`J’ai trouvé plusieurs items correspondant clairement à « ${label} » :`;return{kind:"results",text,items:rows,analysis,results:selected,alternatives:found.alternatives||[],context:{lastItemIds:rows.map(row=>row.id)}};}
  const terms=question=>{const a=analyze(question);return[...a.typeTerms,...a.productTerms,...a.qualifiers];};
  const intents=question=>{const primary=detectIntent(question,quantityFrom(question));return{existence:primary==="existence",quantity:primary==="quantity"||primary==="sufficiency",location:primary==="location",search:primary==="search",sufficiency:primary==="sufficiency"};};
  return{SYNONYMS,SCIENTIFIC_SYNONYMS,ROMAN,UNIT_FACTORS,normalize,repaired,terms,intents,quantityFrom,detectScientific,detectIntent,analyze,expansions,distance,documentFor,contradiction,scoreItem,searchAnalysis,search,convertQuantity,sufficiencyText,answer};
});
